name=VGA_ESP32S3
version=1.0.0
author=SunStar
maintainer=pavel_sunstar@mail.ru
sentence=This is a sample Arduino library for ESP32-S3 VGA output.
paragraph=Provides VGA support for ESP32-S3 microcontroller.
category=Display
url=https://github.com/PavelSunStar/VGA_ESP32S3
architectures=esp32
